### PR TITLE
Refresh plugin 2023

### PR DESCRIPTION
**Pull request by jonesbusy**
Refresh the plugin pom for 2023 (bom, incremental, modern Jenkins etc...)

If ok for you @damianszczepanik I can also be maintainer of this plugin to keep it up-to-date.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jonesbusy** [comment]
Build is failing because I'm not maintainer of this project and cannot update Jenkinsfile

**Comment by damianszczepanik** [comment]
> Build is failing because I'm not maintainer of this project and cannot update Jenkinsfile

I don't think this is true reason of the failure:

`[2023-02-10T17:18:51.685Z] Caused by: java.lang.UnsupportedClassVersionError: org/jenkinsci/maven/plugins/hpi/ValidateMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

**Comment by jonesbusy** [comment]
> > Build is failing because I'm not maintainer of this project and cannot update Jenkinsfile
> 
> I don't think this is true reason of the failure:
> 
> `[2023-02-10T17:18:51.685Z] Caused by: java.lang.UnsupportedClassVersionError: org/jenkinsci/maven/plugins/hpi/ValidateMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> `

It is actually. Because current Jenkins Core doesn't support JDK 8 anymore. We must compile with minimum JDK 11.

**Comment by damianszczepanik** [comment]
I'm not surprising about that because of https://www.jenkins.io/blog/2022/06/28/require-java-11/

The question is why your PR does not work with new JDK ?

**Comment by jonesbusy** [comment]
It works with JDK 11 and JDK 17. But not 8.

Old Jenkinsfile is still used. An administrator should restart the build or a maintainer should commit only the Jenkinsfile.

Error cannot be more clear 

```
18:16:54  Obtained Jenkinsfile from 20885ec475a859ef50e2c2156a260ae183b1dced
18:16:54  ‘Jenkinsfile’ has been modified in an untrusted revision
```

**Comment by damianszczepanik** [comment]
This is not problem with Jenkinsfile - I have used yours and it builds against configurations which you declared https://github.com/jenkinsci/build-name-setter-plugin/pull/74/checks?check_run_id=11340140063

So the problem is with other dependencies which come with your PR

**Comment by jonesbusy** [comment]
Superseded by https://github.com/jenkinsci/build-name-setter-plugin/pull/76

**Pull request closed without merging**
