### PR TITLE
update token-macro version requirement to 2.15

### PR DESCRIPTION
**Pull request by paulvi**
Because using even older 2.13 token macro plugin makes build unstable, see #62 
So this plugin should clearly require specific newer token macro plugin, which is 2.15 currently

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
update version in pom.xml
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by damianszczepanik** [comment]
Dependencies are changing almost every release so this will valid till next release :(

**Comment by paulvi** [comment]
sure, also #66 already has this change

**Comment by paulvi** [comment]
though within this PR README is modified to add CHANGELOG section, see #67

**Comment by damianszczepanik** [comment]
Should be already solved by https://github.com/jenkinsci/build-name-setter-plugin/pull/66

**Comment by paulvi** [comment]
yep,

though within this PR README is modified to add CHANGELOG section, see #67

**Pull request closed without merging**
