### PR TITLE
Added missing dependency to matrix-project-plugin.

### PR DESCRIPTION
**Pull request by uhafner**
This plug-in is not part of the default installation anymore.

Breaks 2 JobDSL test cases, see https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness-stable/1596/testReport/

Followup to jenkinsci/acceptance-test-harness#337

### CODE REVIEW

**Comment by uhafner** [comment]
@olivergondza since you where the last committer and there seems no other activity anymore: should I merge and release the change or should we wait for the original maintainer (the previous commits where from @Le0Michine)

**Comment by olivergondza** [comment]
I have re-enabled the CI job and the PR is failing. It seems to require more love to bump the core version. Is it needed, btw? I would prefer more conservative baseline, say, 1.609?

**Comment by uhafner** [comment]
Hmm, am I missing something obvious? It perfectly builds on my machine :-(

**Comment by olivergondza** [comment]
Thanks, released as 1.6.7.

**Comment by uhafner** [comment]
Interesting, you can release a new version without being member of https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-build-name-setter.yml?

**Comment by olivergondza** [comment]
@uhafner, There is some exception for me as a Release officer.

**Pull request closed without merging**
